version: "3.2"

services:
    db:
        image: mongo
        restart: unless-stopped
        volumes:
            - /data/blog:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: marco
            MONGO_INITDB_ROOT_PASSWORD: icjSnpQ5Gj7^WdbuxWWkUy2qmN$uU7#C
            MONGO_INITDB_DATABASE: blog
        networks:
            - local-network
        container_name: db

    portfolio:
        image: marcojonudo/portfolio
        restart: unless-stopped
        ports:
            - "8083:8090"
        networks:
            - local-network
        depends_on:
            - db
        container_name: portfolio

networks:
    local-network:
        driver: bridge
