version: "3.2"

services:
#    nginx:
#        image: nginx
#        container_name: nginx
#        networks:
#            - local-network

    db:
        image: postgres
        restart: always
        volumes:
            - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
#        volumes:
#            - "/var/data/postgres:/var/lib/postgresql/data"
        container_name: db
        environment:
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        networks:
            - local-network

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        networks:
            - local-network

    blog-api:
        image: marcojonudo/blog-api
        restart: always
        container_name: blog-api
        environment:
            - MAX_MEMORY=128m
#            - ENV=prod
#        volumes:
#            - /u/projects/db-api/logs:/logs
        ports:
            - "8090:8090"
        networks:
            - local-network
        depends_on:
            - db

networks:
    local-network:
        driver: bridge
