micronaut:
    application:
        name: blog-api
    server:
        cors:
            enabled: true
        port: 8090
    router:
        static-resources:
            default:
                mapping: /**
                paths: [classpath:static]

endpoints:
    beans:
        enabled: true
        sensitive: false
    info:
        enabled: true
        sensitive: false
    health:
        enabled: true
        sensitive: false
    refresh:
        enabled: true
        sensitive: false
    routes:
        enabled: true
        sensitive: false
    loggers:
        enabled: true
        sensitive: false

flyway:
    datasources:
        default:
            enabled: true

db:
    url: ${DB_URL:localhost}
    port: ${DB_PORT:5432}
    credentials:
        username: postgres
        password: root

datasources:
    default:
        url: jdbc:postgresql://${db.url}:${db.port}/blog
        username: ${db.credentials.username}
        password: ${db.credentials.password}
        driverClassName: org.postgresql.Driver
