micronaut:
    application:
        name: blog-api
    server:
        cors:
            enabled: true
        port: 8090
    router:
        static-resources:
            default:
                mapping: /blog/**
                paths: [classpath:blog]

endpoints:
    beans:
        enabled: true
        sensitive: false
    info:
        enabled: true
        sensitive: false
    health:
        enabled: true
        sensitive: false
    refresh:
        enabled: true
        sensitive: false
    routes:
        enabled: true
        sensitive: false
    loggers:
        enabled: true
        sensitive: false
flyway:
    datasources:
        default:
            enabled: true

db:
    url: ${DB_URL:localhost}
    port: ${DB_PORT:5432}
    credentials:
        username: postgres
        password: root

datasources:
    default:
        #    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
        #    username: ${JDBC_USER:sa}
        #    password: ${JDBC_PASSWORD:""}
        #    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
        url: jdbc:postgresql://localhost:5432/blog
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver

#dataSource:
#    dbCreate: validate
#    driverClassName: org.postgresql.Driver
#    dialect: org.hibernate.dialect.PostgreSQL10Dialect
#    url: jdbc:postgresql://${db.url}:${db.port}/blog
#    username: ${db.credentials.username}
#    password: ${db.credentials.password}
#    properties:
#        initialSize: 1
#        maxActive: 1
#        minIdle: 1
#        maxIdle: 1
#        testOnBorrow: true
#        validationQuery: SELECT 1
#        validationInterval: 15000
#    logSql: true
