micronaut:
    application:
        name: portfolio
    server:
        cors:
            enabled: true
        port: 8080
    router:
        static-resources:
            default:
                mapping: /blog/**
                paths: [classpath:blog]

endpoints:
    beans:
        enabled: true
        sensitive: false
    info:
        enabled: true
        sensitive: false
    health:
        enabled: true
        sensitive: false
    refresh:
        enabled: true
        sensitive: false
    routes:
        enabled: true
        sensitive: false
    loggers:
        enabled: true
        sensitive: false

#host:
#    ip: ${HOST_IP:localhost}
#    local-mysql-port: ${MYSQL_PORT:3306}
#
#database:
#    credentials:
#        username: root
#        password: root

#hibernate:
#    hbm2ddl:
#        auto: 'none'
#
#dataSource:
#    dbCreate: validate
#    driverClassName: com.mysql.jdbc.Driver
#    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    url: jdbc:mysql://${db.ip}:${db.port}/portfolio?useSSL=false&serverTimezone=Europe/Madrid
#    username: ${database.credentials.username}
#    password: ${database.credentials.password}
#    properties:
#        initialSize: 1
#        maxActive: 1
#        minIdle: 1
#        maxIdle: 1
#        testOnBorrow: true
#        validationQuery: SELECT 1
#        validationInterval: 15000
#    logSql: true
